spring:
  application:
    name: spring-web
  web:
    locale: fr-FR
    locale-resolver: fixed
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 12MB
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /v1

# OPEN API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

# EXTERNAL APIs
api:
  json-placeholder:
    base-url: "https://jsonplaceholder.typicode.com"

# CORS
web:
  cors:
    allowed-origins: "http://www.mywebsite.com"
    allowed-methods: GET, POST, PATCH, PUT, DELETE
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
